aprenda-git/pull-request

assinaturas/facelessOldWoman-7463.md
=> Adiciona assinatura facelessoldwoman

assinaturas/AndeCardoso-1202.md
=> adiciona assinatura AndeCardoso

assinaturas/alisuSantana-1234.md
=> Adicionando assinatura AlisuSantana

assinaturas/eduardoRodrigues-1998.md
=> Adiciona assinatura eduardoRodrigues-1998

assinaturas/vinicusgb-0186.md
Se aceito, este commit adiciona a assinatura de VinicusGB
=> Adiciona assinatura VinicusGB

assinaturas/deiameinhart-0809.md
Meu nome é Andréa, todos me chamam de Deia!
[Meu site é](http://www.andrea.des.br/) lá você conhece um pouco do meu trabalho como designer.
Esse é meu primeiro pull request.
=> adiciona nova assinatura deia meinhart

assinaturas/WirisWernek-0212.md
=> Adiciona Assinatura WirisWernek

assinaturas/StephHoel-1996.md
=> Adiciona assinatura StephHoel

assinaturas/Nome MATHEUS ALBUQUERQUE.md
=> Assinando meu nome

assinaturas/moisesAlves-5567.md
=> Moises esteve aqui

.github/ISSUE_TEMPLATE/m--conduta.md, assinaturas/RafaelMota-2021.md
Atualizei a ortografia da palavra "descriminação" para "discriminação", pois têm significados diferentes (eu não sabia disso). Espero que esteja correto e fico feliz em poder ajudar.
=> Altera ortografia

assinaturas/RafaelMota-2021.md
=> Adiciona a assinatura de Rafael Mota

assinaturas/Ulisses-1985.md
- [ *] Eu segui o [formato sugerido](https://github.com/aprenda-git/pull-request/blob/main/assinaturas/README.md)
- [ *] Não usei palavras ofensivas
- [ *] Não deletei nenhum arquivo
=> Adiciona assinatura ulisses malanski

assinaturas/pedroJose-8846.md
=> Adiciona a assinatura de Pedro José

assinaturas/EduardoKayke-7777.md
Sou o Eduardo, aluno de Desenvolvimento Web.
Adicionei arquivo README.md na pasta de assinaturas.
=> Adiciona README de PullRequest do EduardoKayke

assinaturas/hiltonmm-1982.md
=> Adiciona assinutra de Hilton Moreira

assinaturas/hugo-rodrigues-0110.md
=> Adiciona assinatura hugo-rodrigues-0110.md

assinaturas/MarceloCodigos-1992.md
Adicione um arquivo [markdown](https://guides.github.com/features/mastering-markdown/) na pasta `assinaturas` contando um pouco mais sobre você. 
=> Adiciona assinatura MarceloCodigos-1992

assinaturas/raulfonseca-1994.md
=> Adicionada raulfonseca

assinaturas/nnilux-0087.md
=> Pull Request nnilux

assinaturas/RTuratti-1995.md
=> Adicionar assinatura RTuratti

assinaturas/jfpresotto-1991.md
=> adiciona jfpresotto-1991.md

assinaturas/phRodovalhoo-1998.md
=> Adiciona assinatura phRodovalho-1998

assinaturas/GuilhermeHenriquePereiraPostinico-1996.md
=> Adiciona guilherme-henrique-pereira-postinico-1996

assinaturas/elinaldojr-1988.md
=> Adiciona assinatura elinaldojr

assinaturas/alyson-4521.md
=> adciona alyson

assinaturas/AndersonSSH.md
=> adicona assinatura andersonssh

assinaturas/RobsonEduardo0016.md
=> Adicionando Robson Eduardo

assinaturas/Aquiles_Mauro_7894.md
=> Adiciona assinatura de Aquiles_Mauro_7894

assinaturas/RodrigoVenancio.md
=> adiciona assinatura RodrigoVenancio

assinaturas/RodrigoRuivo-1908.md
=> Adiciona assinatura Rodrigo.Ruivo1908

assinaturas/Bryan_Patucci_1102.md
=> Adiciona assinatura BryanPatucci

assinaturas/davimm96.md
=> Adiciona assinatura davimm96

assinaturas/Allan_Verde-2000.md
=> Adiciona assinatura allan-verde

assinaturas/icaroeloi-2598.md
=> adiciona assinatura icaroeloi-2598

assinaturas/romarioCosta-2509.md
=> Adiciona assinatura RomasCosta

assinaturas/luizTerra.md
=> Adiciona assinatura luiz terra

assinaturas/veniciocosta150595.md
=> Adiciona assinatura veniciocosta

assinaturas/ElvisMaicol-1980.md
=> Adiciona assinatura ElvisMaicol

assinaturas/DeysiLopes.md
=> Adiciona assitura DeysiLopes

assinaturas/vlcp197-1997.md
=> Adiciona assinatura vlcp197

assinaturas/HenriqueGibi.md
Conte um pouco mais sobre você!
=> Adiciona assinatura HenriqueGibi.md

assinaturas/Atanes-Trybe.md
=> Atanes-Trybe inclusão de assinatura!

assinaturas/ErimilsonSilva-982212.md
=> Erimilson-Silva-pull-request

assinaturas/jluizjs-1305.md
=> Adiciona assinatura jluizjs

assinaturas/julianocanuto-2021.md
- [ x ] Dei o [nome correto](https://github.com/aprenda-git/pull-request/tree/main/assinaturas/nome-arquivo.md) ao meu arquivo.
=> Adiciona assinatura julianocanuto-2021

assinaturas/PauloAndreCocco.md
=> Adiciona assinatura de Paulo André Cocco

assinaturas/BrunoSantiago-1990.md
=> Adiciona assinatura BrunoSantiago-1990

assinaturas/PauloBacalhau_1962.md
- [ x ] Dei o [nome correto](https://github.com/aprenda-git/pull-request/tree/main/assinaturas/nome-arquivo.md) ao meu arquivo.
=> Adicionando arquivo paulobacalhau_1962.md com meus dados

assinaturas/LeandroBRodrigues-0702.md
=> adição do README do perfil LEandroBRodrigues

assinaturas/Jose1113.md
=> Adiciona assinatura Jose1113

assinaturas/AmandaPagani-7113.md
=> Adiciona apresentacao AmandaPagani-7113.md

assinaturas/MayconL-2727.md
=> Adiciona assinatura MayconL27

assinaturas/wendreof-1993.md
=> Adicionado: Assinatura wendreof

assinaturas/AdevanNeves.md
- [ x ] Dei o [nome correto](https://github.com/aprenda-git/pull-request/tree/main/assinaturas/nome-arquivo.md) ao meu arquivo.
=> Adiciona na pasta assinaturas o arquivo AdevanNeves.md

assinaturas/AntonioNeto-2000.md
=> Adiciona Antonio Neto

assinaturas/cecilia-brito-2506.md
=> Adicionando assinatura cecilia brito

assinaturas/PedroHLopes-1501.md
=> Adiciona assinatura pedrohlopes

assinaturas/LucianaLemos-1996.md
=> Adiciona assinatura Luarlemos (Luciana Lemos)

assinaturas/PaolaRodrigues-0017.md
- [X ] Dei o [nome correto](https://github.com/aprenda-git/pull-request/tree/main/assinaturas/nome-arquivo.md) ao meu arquivo.
- [X ] Eu segui o [formato sugerido](https://github.com/aprenda-git/pull-request/blob/main/assinaturas/README.md)
- [X ] Não usei palavras ofensivas
- [X ] Não deletei nenhum arquivo
=> Adiciona assinatura paolarodrigues

assinaturas/AlessandroCosta-0107.md
=> Adicona assinatura

assinaturas/JoaoFerrazfs.md
=> Adiciona assinatura JoaoFerrazfs

assinaturas/igor-1029.md
=> tutorial-top-demais

assinaturas/ViniciusRubia-1452.md
=> Adicona assinatura Vinicius Rubia

assinaturas/Italo Carvalho.md
=> Adiciona assinatura Ítalo Carvalho

assinaturas/demiank-0615
=> commit do demian

assinaturas/davihenrique1996.md
=> Adiciona assinatura davi henrique

assinaturas/JacksonNascimento-7462.md
=> Adiciona assinatura Jackson Nascimento

assinaturas/AndersonRodriguess-1992.md
=> Adiciona assinatura AndersonRodriguess

assinaturas/Enriq4472.md
=> Adiciona assinatura Enriq4472

assinaturas/LeandroOliveira-1903.md
=> Adicona leandro oliveira

assinaturas/KeiteMNPassos.md
=> Adiciona keitepassos

assinaturas/Margarida-1999.md
=> Se aceite, adiciona minha assinatura

assinaturas/miller-1408.md
=> add assinatura Miller-1408

assinaturas/miller-1408.md, pull_request_template.md
=> correção template

assinaturas/mateusInacio-0607.md
=> Adiciona assinatura mateusinacio

assinaturas/LucasLM1-1213.md
=> Adiciona assinatura LucasLM1

assinaturas/brunoluizgn-180389.md
=> adiciona assinatura brunoluizgn

assinaturas/brunogssouza-1610.md
- [x ] Eu segui o [formato sugerido](https://github.com/aprenda-git/pull-request/blob/main/assinaturas/README.md)
=> Adicionando a assinatura de: brunogssouza.md

assinaturas/GabrielFtsa-2004.md
=> Adiciona Assinatura GabrielFtsa

assinaturas/anaBeatriz-0022.md
=> Criando uma nova branch

assinaturas/BrunoWilian.md
=> brunowilian

assinaturas/gabrielLucas-2412.md
=> Adiciona assinatura gglsilva

assinaturas/Fernando-CR019.md
Conte um pouco mais sobre você!
=> Adiciona assinatura Fernando-CR019.md

assinaturas/PatrickMarques-PkMs7.md
=> Adiciona novo integrante, PatrickMarques-PkMs7.md

assinaturas/GabrielFucci-4821.md
=> Adiciona assinatura Gabriel Fucci

assinaturas/J-Barboza.md
=> Adiciona assinatura J-Barboza

assinaturas/WesleysPaiva2007.md
- [x ] Eu segui o [formato sugerido](https://github.com/aprenda-git/pull-request/blob/main/assinaturas/README.md)
=> adiciona assinatura WesleysPaiva2007.md

assinaturas/Isaac-1387645.md
=> Adiciona assinatura Isaac-1387645

assinaturas/Brenolor-1997.md
=> Adiciona assinatura brenolor

assinaturas/vitor-almeida-2000.md
=> chore: add vitor almeida's signature

assinaturas/fabianocsouza-0130.md
=> adiciona assinatura fabianocsouza

assinaturas/diogorodrigues.md
=> Adiciona assinatura Diogo

assinaturas/canutoIlberto-0001.md
=> Adiciona assinatura canutoilberto

assinaturas/hugoscode0007.md
=> MuitoIradoTutorial

assinaturas/marden_coelho.md
=> Adiciona assinatura marden_coelho

assinaturas/guilhermyAraujo-991.md
=> adiciona assinatura guilhermyAraujo-991.md

assinaturas/RenatoCarvalho.md
=> Adiciona assinatura RenatoCarvalho

assinaturas/eduardoJC.md
=> Adiciona eduardo jc

robert-argolo-1994.md
=> Adiciona assinatura Robert Argolo

assinaturas/Gabriel-Marino-1710.md
EDIT: fui na ansiedade e nem li o template direto, só li os check marks. Vou colocar aqui o mesmo que coloquei na minha assinatura, sobre mim: Bem eu sou um estudante de Bacharel em Física e a situação atual da ciência no Brasil não me anima muito, então eu estou aprimorando meus conhecimentos e então tentar a sorte na area de desenvolvimento de software.
=> Adiciona minha assinatura (Gabriel-Marino-1710)

assinaturas/ernani-rosa-8991.md
Olá! Estou concluindo o curso de Git e Github. Obrigado Perkles!
Segue meu PR com minha assinatura.
=> Adiciona minha assinatura

assinaturas/AdsandroCarvalho-0112.md
=> Adiciona assinatura: Adsandro

assinaturas/IvanNalon.md
=> Adiciona assinatura Ivan Nalon

assinaturas/JoãoPedroAlmeida-1999.md
=> Adiciona assinatura João Pedro Almeida

assinaturas/SamuelOliveira-2912.md
Adicionado novo arquivo "SamuelOliveira-2912.md" na pasta /assinaturas
Muito obrigado pelo curso. Está me ajudando e estou repassando seu
conteudo para mostrar git para desenvolvedores Cobol.
- [ x] Eu segui o [formato …
=> Adicionar novo usuario na pasta assinatura

assinaturas/veronicaDeAlmeida-1982.md
=> Adiciona assinatura da Veronica de Almeida

assinaturas/karenbiblio-3891.md
=> Adiciona karenbiblio-3891

assinaturas/wellinton-1995.md
=> adiciona assinatura wellinton-1995

assinaturas/luanaMorais-1992.md
=> Adiciona assinatura luanamorais1992

.idea/.gitignore, .idea/misc.xml, .idea/modules.xml, .idea/pull-request.iml, .idea/vcs.xml, assinaturas/mauroBiazutti-1987.md
=> Adiciona maurobiazutti

assinaturas/brunotr-0027.md
=> Adiciona assinatura bruno

assinaturas/EltonDuarte-0007.md
=> Adiciona assinatura Elton Duarte

assinaturas/Akira-0815.md
=> Adiciona assinatura akira-8015

assinaturas/eu.md
=> aprendendo

assinaturas/TiagoAlves-2309.md
=> Adicionar assinatura do Tiago Alves

assinaturas/Meszengisser-9999.md
=> Meszengisser´s Signature

assinaturas/EduardoCostaEXE.md
=> Minha assinatura

assinaturas/enricocasaquia-0750.md
=> upload arquivo markdown

assinaturas/BarrosEdneudo.md
=> Adiciona assinatura de BarrosEdneudo

assinaturas/israelAssis-1987.md
=> Adiciona assinatura israelAssis-1987

assinaturas/LetyHashimoto-0023.md
=> first contribution

assinaturas/alanocs-2022.md
=> Assinatura Alan Silva

assinaturas/GaBrIeL-ROSSI-8365.md
=> adiciona assinatura Gabriel-Rossi

assinaturas/cdmaria-04135.md
=> adciona CD-MARIA

assinaturas/João_Gabriel_Dal_Forno.md
=> adicionei meu nome

assinaturas/jhonatavbrg-4242.md
=> chore: add sign jhonatavbrg

assinaturas/LeonardoCavi-1900
=> Adiciona a assinatura LeonardoCavi-1900

assinaturas/natanmedrado-0051.md
=> Adiciona assinatura natanmedrado-0051

assinaturas/MicaelOrtega-0628.md
=> Adiciona assinatura MicaelOrtega

assinaturas/DanielAleixo-1993.md
=> Adiciona assinatura DanielAleixo-1993

assinaturas/jeffemart.md
=> Adiciona assinatura jeffemart

assinaturas/ewelynsamaris-1416.md
=> Adiciona assinatura de Ewelyn Sâmaris

assinaturas/patrickmanzo-0322.md
=> Adicionando assinatura patrickmanzo

assinaturas/caioAmoedo-1350.md
=> Adiciona assinatura caioamoedo

assinaturas/romarioOliveira9-2706.md
=> Adiciona assinatura romariooliveira9

assinaturas/Sanjijito-8585.md
=> Adiciona sanjijito

assinaturas/Guilherme-Domingues2592.md
=> Adiciona assinatura Guidomingues

assinaturas/AbnerAndrade-1022.md
=> Adiciona assinatura de Abner Andrade

assinaturas/bhavya-3456.md
=> bhavya-3456

assinaturas/droperox-2022.md
- [x ] Eu segui o [formato sugerido](https://github.com/aprenda-git/pull-request/blob/main/assinaturas/README.md)
=> Adiciona assinatura droperox-2022

assinaturas/iuriSalgado-0291.md
=> Adiciona assinatura Iuri Salgado

assinaturas/charles-1616.md, charles-1616.md
=> charles 1616

assinaturas/NathaliaBuchholz-3110.md
=> Adiciona assinatura nathalia buchholz

README.md
Resolve o apontamento deixado por @natan20200679 e complementa o README.md com a descrição adequada.
ref: #195
=> resolves #195

README.md
O tutorial ainda continha referencia a nomeacao do arquivo usando um numero randomico. Modificado para colocar somente o nickname do GitHub.
=> complementa tutorial README

assinaturas/vinicius-maciel.md
=> Adiciona assinatura vinicius-maciel

assinaturas/HugoVasc.md
=> Adiciona assinatura de Hugo Vasconcelos

assinaturas/joaofmds.md
=> Adiciona assinatura joaofmds

assinaturas/gabrieldelucca-1996.md
=> Adiciona assinatura gabrieldelucca-1996

assinaturas/nakaDrigo.md
=> Adiciona arquivo de assinatura

assinaturas/ReginaldoVillela.md
=> Adiciona assinatura Reginaldo Villela

assinaturas/DaviAlves123.md
=> Adiciona assinatura Davi

assinaturas/Cristina_Aoki.md
=> adiciona assinatura Cristina Aoki

assinaturas/EduardoSchmitz.md
=> Adicion assinatura EduardoSchmtz

assinaturas/RodrigoMaia.md
=> Adiciona assinatura rodrigomaia

assinaturas/ggarpelli.md
=> assinatura do GG

assinaturas/ChrisKryon.md
=> add a generated readme.me generated on rahuldkjain.github.io

assinaturas/Misael-Almeida.txt
=> inclusão da minha assinatura no diretório assinaturas

assinaturas/MieleSantos.md
=> Adicionando arquivo assinatura com sobre mim

assinaturas/LucasAragao.md
=> Adiciona assinatura LucasAragao

assinaturas/douglastos.md
=> adiciona assinatura douglastos.md

assinaturas/guilhermetonelotti-6432.md
=> Adiciona assinatura guilherme tonelotti

assinaturas/silviaZAlbuq.md
`Conte` um pouco mais sobre voce!
=> Adiciona assinatura SilviaZ

assinaturas/renata-uzeda.md
-  [x] Dei o [nome correto](https://github.com/aprenda-git/pull-request/tree/main/assinaturas/nome-arquivo.md) ao meu arquivo.
-  [x] Eu segui o [formato sugerido](https://github.com/aprenda-git/pull-request/blob/main/assinaturas/README.md)
-  [x] Não usei palavras ofensivas
-  [x] Não deletei nenhum arquivo
=> Adiciona assinatura renata-uzeda

assinaturas/barolohelio.md
=> Adicionando assinatura Hélio Barolo

assinaturas/HerissonS-1999.md, assinaturas/HerissonS.md
=> Adiciona assinatura herisson

assinaturas/petersousa.md
=> Adiciona assinatura petersousa

assinaturas/talles2512.md
=> Adiciona assinatura talles2512

assinaturas/calimanfilho.md
Conte um pouco mais sobre você!
=> Adiciona assinatura calimanfilho

assinaturas/fsantana.md
=> Adiciona assinatura fsantana

assinaturas/GlaucioDrumond-1108.md
=> Adiciona assinatura GlaucioDrumond-1108

assinaturas/luizeduardoraposo.md
=> Adiciona assinatura luizeduardoraposo

assinaturas/MrtheLoop.md
Nome: Matheus da Silva Salvador
Comida Favorita: Carne Moída, Pizza e Bolo de Cenoura
Aprendendo: Git & Github, Python, Pentest & Hacking e Linux
Sobre mim: sou fascinado por hacking, cibersegurança e Linux. Esse apelido se dá
pois no meu primeiro dia de serviço, eu dei um Loop na rede de um condomínio.
- [ X] Dei o [nome correto](https://github.com/aprenda-git/pull-request/tree/main/assinaturas/nome-arquivo.md) ao meu arquivo.
- [ X] Eu segui o [formato sugerido](https://github.com/aprenda-git/pull-request/blob/main/assinaturas/README.md)
- [ X] Não usei palavras ofensivas
- [ X] Não deletei nenhum arquivo
=> Adiciona MrtheLoop

assinaturas/esioDesynC.md
Conte um pouco mais sobre você!
=> Adiciona o arquivo esioDesynC.md no diretório assinaturas

assinaturas/RobertoTeixeira.md
=> Robertoteixeira

assinaturas/douglasjason7.md
=> Adiciona assinatura douglasjason7

assinaturas/DayvisonFavacho.md
=> adiciona assinatura DayvisonFavacho

assinaturas/Paucinha40.md
=> Adiciona assinatura Paucinha40

assinaturas/KevSoares.md
=> Adiciona assinatura KevSoares.md

assinaturas/leandro-mnc.md
=> Adiciona assinatura de leandro-mnc.md

assinaturas/JoaoPedroV.md
=> Adiciona João Pedro

assinaturas/IgorSAssis.md
=> adiciona nova assinatura

assinaturas/danietakeshi-1909.md
=> Adiciona assinatura danietakeshi

assinaturas/3ielzinh.md
=> Adiciona assinatura 3ielzinh

assinaturas/JessicasNascimento.md
=> Assinatura JessicasNascimento

assinaturas/ThiagoSousa81.md
=> 	new file:   assinaturas/ThiagoSousa81.md

assinaturas/DioAugust-2002.md, assinaturas/rhaizaOliveira-1990.md
=> Adiciona assinatura DiohAugust

assinaturas/CarlosAlberto-2023.md
=> Adiciona assinatura Carlos

assinaturas/MMagnun.md, assinaturas/Misael-Almeida.md
=> Magnun branch pull request

assinaturas/marcielCarvalho.md
=> Adiciona assinatura marcielcarvalho

assinaturas/tiago-play.md
=> Adiciona assinatura tiago-play

assinaturas/lincolngondin.md
=> Meu primeiro pull-request

assinaturas/JairGino.md
=> add JairGino to assinaturas directory

assinaturas/mariliacosta-1991.md
=> adiciona assinatura mariliacosta1991

assinaturas/Jncarvalho-1990.md
=> Adiciona assinatura Jncarvalho-1990

assinaturas/rafael-motta1997.md
=> Adiciona assinatura rafael-motta1997

assinaturas/ThiagoSousa81.md
=> minha segunda pull request

assinaturas/suyaneandressa.md
=> Adiciona assinatura suyaneandressa.md

assinaturas/Leandro117.md
=> Adiciona assinatura Leandro117.mb

assinaturas/ViFMarques.md
=> Adiciona assinatura ViFMarques

assinaturas/Lin.md
=> Adicionado Lin.md

assinaturas/ArturCarvalho0.md
=> Adiciona assinatura ArturCarvalho0

assinaturas/Mkoseki125-1801.md
=> Adiciona assinatura Mkoseki125

assinaturas/RodrigoGuimaraes.md
=> Adiciona assinatura RodrigoGuima

assinaturas/rickomad-1991.md
=> Adiciona assinatura ricknomad

assinaturas/YghoPereira.md
=> adiciona arquivo YghoPereira.md

assinaturas/alyssonMacharete-2508.md
=> Adiciona assinatura Alysson

assinaturas/lucaswenderson.md
=> Nova assinatura: Lucas Wenderson

assinaturas/Aranjhonn-7371.md
=> Adiciona assinatura Aranjhonn Araujo

assinaturas/GustavoRamos-2609.md
=> Adiciona assinatura GustavoRamos-26-09

assinaturas/LuanaMelo.md
=> assinatura de Luana Melo

assinaturas/matheusGomes-1994.md
=> Adiciona assinatura matheusGomes

assinaturas/AlberthADS.md
=> Adiciona assinatura AlberthADS

assinaturas/miguel.md
=> nova branch adicionada

assinaturas/diogs.md
=> Adiciona assinatura diogs

assinaturas/boloDePote-1987.md
=> feat: bolinho de pote

assinaturas/LuizFCS.md
=> Adiciona assinatura LuizFCS

assinaturas/RafaelLira-1701.md
=> Adiciona assinatura rafaellira-1701

assinaturas/emifgarcia.md
=> add assinatura-emifgarcia

assinaturas/pablo_stacks.md
Adicione um arquivo [markdown] ----> ('feito...')
Só serão aceitos pull requests dentro da pasta `assinaturas`. ------> ('Ok')
Para sugerir edições no [tutorial](https://github.com/aprenda-git/pull-request/blob/main/README.md) sobre pull request abra uma [issue](https://github.com/aprenda-git/pull-request/issues) 
- [ x ] Dei o [nome correto](https://github.com/aprenda-git/pull-request/tree/main/assinaturas/nome-arquivo.md) ao meu arquivo.
- [ x ]  Não deletei nenhum arquivo
=> Meu primeiro pull-request!

assinaturas/Tacoberries.md
=> testando essa lambança*

assinaturas/jeoliveira045.md
=> adiciona markdown da conta jeoliveira045

assinaturas/Meu nome é Éder.md
=> Adiciona assinatura EderCastro2402

assinaturas/leonardo-vian.md
=> adiciona markdown da conta leonardo-vian

assinaturas/KirinRyu.md
- [x ] Eu segui o [formato sugerido](https://github.com/aprenda-git/pull-request/blob/main/assinaturas/README.md)
=> Adciona kirinryu

assinaturas/kirquia.md
=> Adiciona kirquia.md à pasta assinaturas

assinaturas/JosielJrr.md
=> Adiciona assinatura JosielJrr

assinaturas/mf-guilherme.md
=> Adiciona assinatura MF-Guilherme

assinaturas/clauribeirodevjava
=> Aprendendo pull requeest

assinaturas/DouglasFernandes.md
=> Minha assinatura Douglas

assinaturas/cauaEmanuel.md
=>  adiciona assinatura caua emanuel

assinaturas/Kiri.md
=> minhamensagemdecommit

assinaturas/AugustoJesus-2710.md, assinaturas/cauaEmanuel.md
=> build: Trocando meu nome

assinaturas/LilianMS.md
=> :sparkles: feat: add file LilianMS.md

assinaturas/blueaxolotlbr.md
=> Adiciona assinatura blueaxolotlbr
